### ISSUE TITLE
no such file or directory: ./response/master_all

### ISSUE THREAD

**Issue by aa13058219642** [kushieda-minori/vc_file_grouper#20]
Hi,
I download your application, but I don't know how to run.
it's tell me "no such file or directory: ./response/master_all"
the page "http://localhost:8585/config/" need a data path, but
where is the file? how can I get it?

Thanks

**Comment by kushieda-minori** [comment]
It's part of the VC game data. You need to extract it. There are some directions on the wiki

**Comment by aa13058219642** [comment]
your software are very useful, thank you.

here I have a question:
has a way to download all HD card(640*896)? if you no have the card in the accont ?

**Comment by johnjaylward** [comment]
no, at the moment I don't have any tools in place to fetch new/missing HD images. There are a few users on the wiki who have tools that can pull those, but I've never looked into it.
