### ISSUE TITLE
images path gets cut by 1 character

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#27]
The images pages (havent confirmed all, but at least http://localhost:8585/images/event/ and http://localhost:8585/images/item/) generate image links that are missing 1 character, resulting in broken images.

the paths are e.g.
http://localhost:8585/images/event/dvertisement/1/banner_en
http://localhost:8585/images/item/eck/301

instead of

http://localhost:8585/images/event/advertisement/1/banner_en
http://localhost:8585/images/item/deck/301

correcting the path manually fixes it

can you fix it in the grouper?

**Comment by kushieda-minori** [comment]
@Adriaantje , I'm not able to reproduce this on linux. What OS/browser are you using?

**Comment by Adriaantje** [comment]
`OS Name:                   Microsoft Windows 10 Pro`
`OS Version:                10.0.18362 N/A Build 18362`

`Firefox Quantum 69.0.2 (64-bit)`
and also
`Version 77.0.3865.90 (Official Build) (64-bit)`

I haven't tried on linux or OSX, i'll see how it behaves there

**Comment by kushieda-minori** [comment]
I did have an issue where I had to disable my ad blocker for the site
(localhost). If you are used one, try disabling/whitelisting it too.

**Comment by Adriaantje** [comment]
Disabling adblock didnt fix it for me.
I tried internet explorer in the meantime, and FF and chrome on OSX. all with the same issue.

The same happens when I bypass the browser entirely:
```html
$ curl http://localhost:8585/images/event/
<html>
<head>
        <link rel="stylesheet" type="text/css" href="/css/style.css">
</head>
<body class="stary-night"><div><a href="dvertisement\1\banner_en"><img src="dvertisement\1\banner_en"/></a><br />dvertisement\1\banner_en</div><div><a href="dvertisement\2\banner_en">
```
... etc

**Comment by kushieda-minori** [comment]
Ok, I'll try OSX later as well. Thanks

**Comment by kushieda-minori** [comment]
I believe the issue may be here where I trim the OS root path out:
* https://github.com/kushieda-minori/vc_file_grouper/blob/master/handler/imagehandlers.go#L124
* https://github.com/kushieda-minori/vc_file_grouper/blob/master/handler/strbhandlers.go#L123

Will need to investigate further later

**Comment by kushieda-minori** [comment]
@Adriaantje can you try the executables here: https://github.com/kushieda-minori/vc_file_grouper/releases/tag/v20200129-p1 ?

I tried them on OSX and Windows 10 and didn't seem to have any issues. If they work fine for you I'll merge the changes over and finalize the release.

Thanks.

**Comment by Adriaantje** [comment]
looking good.
I tried on win10 and OSX (mojave) too, and works on both
