### ISSUE TITLE
Bridal Kisaragi and Queen Shion incorrectly named after rebirth added

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#29]
With the latest batch of new rebirths, Bridal Kisaragi and Queen Shion get named Kisaragi and Little Shion in the tool, respectively.

This includes the link to the wiki, and the file names of the images that get downloaded.
Any idea what's causing this?

Kisaragi:
http://localhost:8585/cards/detail/8260

Shion:
http://localhost:8585/cards/detail/8258

**Comment by kushieda-minori** [comment]
the reason appears to be that MyNet misnamed the cards:
```
2019/12/02 19:52:41 Found Card Kisaragi: (8260)
2019/12/02 19:52:41 Card: 6096, Name: Bridal Kisaragi, Evo: 0
2019/12/02 19:52:41 Card: 6097, Name: Bridal Kisaragi, Evo: H
2019/12/02 19:52:41 Card: 6098, Name: Bridal Kisaragi, Evo: G
2019/12/02 19:52:41 Card: 8260, Name: Kisaragi, Evo: X
```
```
2019/12/02 19:53:32 Found Card Little Shion: (8258)
2019/12/02 19:53:32 Card: 5795, Name: Queen Shion, Evo: 0
2019/12/02 19:53:32 Card: 5796, Name: Queen Shion, Evo: H
2019/12/02 19:53:32 Card: 5808, Name: Queen Shion, Evo: G
2019/12/02 19:53:32 Card: 8258, Name: Little Shion, Evo: X
```

I'm not sure I have a solution that would fix both of these...

**Comment by kushieda-minori** [comment]
Best bet would be to open a support ticket with MyNet and have them update the data files with the correct names

**Comment by kushieda-minori** [comment]
for now I'll work around it by using the name of the first evolution
