### ISSUE TITLE
Soul Weapon event ranking reward and point rewards table missing in template

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#30]
Title says it all, the soul weapon event RR and pt reward tables are not present in the template text.
Can you add this?

**Comment by kushieda-minori** [comment]
@Adriaantje, I forgot which event has that. Is it this one: https://valkyriecrusade.fandom.com/wiki/Holy_Shield!_A_Hero! ?

**Comment by kushieda-minori** [comment]
@Adriaantje , have you seen the reward tables in the data files? I don't remember seeing them for the first 2 Soul Weapon events

**Comment by kushieda-minori** [comment]
Ok, I tihnk it's these 2:
* `mst_weapon_arrival_point_reward`
* `mst_weapon_ranking_reward`

but both are blank in the data file from the second event. I'll get a fresh copy from the new event and see if they started populating it.

**Comment by kushieda-minori** [comment]
yeah, @Adriaantje , looks like the data is still empty in the file even for the 3rd event. I did make improvements for how weapon data is handled though, so I'll generate a new release for that shortly.

My best suggestion for handling these large tables would be to build a template for them and just have a set of variables for the items that change event-to-event.

For example of how the wiki handled it before I took over, see some older events:
* https://valkyriecrusade.fandom.com/wiki/Sacred_Beasts_of_the_Forest
    * https://valkyriecrusade.fandom.com/wiki/Template:Rewards5
The `Template:Rewards5` would be what you base the Soul Weapon event rewards on. I'd create a new template called something like `Template:SoulRewards1` and build off of the table you made for the Holy Shield event

**Comment by Adriaantje** [comment]
I see...
I did not look into the data, I just assumed it was there, since the event has RR and pt rewards now.
I'll keep an eye out for it the next time this event comes around

Thanks for looking into it!

**Comment by Adriaantje** [comment]
Looks like the fields are filled now.
I manually made a table for the 3rd event, by copying from the tower/drv pages.
[https://valkyriecrusade.fandom.com/wiki/Holy_Shield!_A_Hero!](https://valkyriecrusade.fandom.com/wiki/Holy_Shield!_A_Hero!)

Is it possible to include these tables in soul weapon events too, now that the data is there?

**Comment by kushieda-minori** [comment]
can you send me a screenshot of what the data looks like for the first few fields of both the `mst_weapon_arrival_point_reward` and `mst_weapon_ranking_reward` tables? I still don't seem them populated and it may just be because I've never played that type of event.

**Comment by Adriaantje** [comment]
certainly.
mst_weapon_arrival_point_reward:
```
$ cat master_all.json.txt | grep -A 50 'mst_weapon_arrival_point_reward'
  "mst_weapon_arrival_point_reward": [
    {
      "_id": 40,
      "group_id": 2,
      "point": 500,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 50000,
      "exp": 0,
      "item_id": -1,
      "card_id": -1,
      "num": 0
    },
    {
      "_id": 41,
      "group_id": 2,
      "point": 1000,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 0,
      "exp": 0,
      "item_id": 12,
      "card_id": -1,
      "num": 3
    },
    {
      "_id": 42,
      "group_id": 2,
      "point": 1500,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 50000,
      "exp": 0,
      "item_id": -1,
      "card_id": -1,
      "num": 0
    },
```

mst_weapon_ranking_reward:
```
$ cat master_all.json.txt | grep -A 50 'mst_weapon_ranking_reward'
  "mst_weapon_ranking_reward": [
    {
      "_id": 36,
      "group_id": 2,
      "rank_from": 1,
      "rank_to": 100,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 0,
      "exp": 0,
      "item_id": -1,
      "card_id": 8396,
      "num": 2
    },
    {
      "_id": 37,
      "group_id": 2,
      "rank_from": 1,
      "rank_to": 100,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 0,
      "exp": 0,
      "item_id": 714,
      "card_id": -1,
      "num": 2
    },
    {
      "_id": 38,
      "group_id": 2,
      "rank_from": 1,
      "rank_to": 100,
      "cash": 0,
      "friend_point": 0,
      "coin": 0,
      "iron": 0,
      "ether": 0,
      "elixir": 0,
      "exp": 0,
      "item_id": 481,
      "card_id": -1,
      "num": 10
    },
```

**Comment by johnjaylward** [comment]
looks like I'll be able to use the same structures I use for the other ranking info tables, so it shouldn't be a huge effort to add in.

Actually, looking closer at the data files now, it looks like they changed how those reward tables work, I don't see any reward data in the "dungeon" (DRV) areas either, but I know I used to...

**Comment by kushieda-minori** [comment]
fixed in 072f70b58d4fa50deb36b570df8b169a90a4735b

**Comment by kushieda-minori** [comment]
give the new release a try and let me know if it works for Soul Weapon event rewards now. I still can't see the ranking data, so I didn't test it.

**Comment by Adriaantje** [comment]
Doesn't look like it. I get:
```

==Rewards==

{| border="1" cellpadding="1" cellspacing="1" class="mw-collapsible mw-collapsed article-table" style="float:left"
|-
! colspan="2"|Point Rewards
|-
! style="text-align:right"|Point
! Reward
|}

{| border="1" cellpadding="1" cellspacing="1" class="mw-collapsible mw-collapsed article-table" style="float:left"
|-
! colspan="2"|Rank Rewards
|-
! style="text-align:right"|Rank
! Reward
|}

{{clr}}
```

If you know a convenient way to transfer 2,5gb, i can send you the data maybe?

**Comment by kushieda-minori** [comment]
I think I see what I missed. I'll re-do the release now. give me about 5 minutes

**Comment by kushieda-minori** [comment]
ok, can you try now?

**Comment by Adriaantje** [comment]
almost, but not entirely.
tables are filled now, but there's some odd stuff in the Pt rewards (unknown reward type and unknown group).
based on the previous EC, the unknown reward should be gems
I couldn't find a template for memory cores, so i just put `|Memory Core Lv.4 x50` last time
```
==Rewards==

{| border="1" cellpadding="1" cellspacing="1" class="mw-collapsible mw-collapsed article-table" style="float:left"
|-
! colspan="2"|Point Rewards
|-
! style="text-align:right"|Point
! Reward
|-
|style="text-align:right"|500
|Unknown Reward Type x0
|-
|style="text-align:right"|1000
|{{Valkyrie|shoeslight}} x3
|-
|style="text-align:right"|1500
|Unknown Reward Type x0
|-
|style="text-align:right"|2000
|{{Valkyrie|swordlight}} x3
|-
|style="text-align:right"|2500
|Unknown Reward Type x0
|-
|style="text-align:right"|3000
|{{Card Icon|Slime Queen}} x5
|-
|style="text-align:right"|4000
|Unknown Reward Type x0
|-
|style="text-align:right"|5000
|{{Valkyrie|shoes}} x1
|-
|style="text-align:right"|7000
|__UNKNOWN_GROUP:_52_Memory Core Lv.4__ x50
|-
|style="text-align:right"|9000
|{{Valkyrie|sword}} x1
|-
|style="text-align:right"|11000
|__UNKNOWN_GROUP:_52_Memory Core Lv.4__ x50
|-
|style="text-align:right"|13000
|{{Card Icon|Slime Queen＋}} x5
|-
|style="text-align:right"|15000
|__UNKNOWN_GROUP:_52_Memory Core Lv.5__ x100
|-
|style="text-align:right"|20000
|{{Ticket|legendary}} x1
|-
|style="text-align:right"|25000
|__UNKNOWN_GROUP:_52_Memory Core Lv.5__ x300
|-
|style="text-align:right"|30000
|{{Ticket|lr chance}} x1
|-
|style="text-align:right"|35000
|__UNKNOWN_GROUP:_52_Memory Core Lv.5__ x500
|-
```

**Comment by kushieda-minori** [comment]
ok, perfect. I'll get that updated and let you know when the release is up. if you want, you can email me just the master_data.json to kushieda@zetsuboushita.net. or maybe send in a PM in discord. if you want to make sure all your personal data is not in it you can remove the `defs` and `defs_tune` keys, but I'm pretty sure it doesn't have any of your account data in it.

**Comment by kushieda-minori** [comment]
Ok, can you check the latest release? If it looks good to you, I'll make that release final

**Comment by Adriaantje** [comment]
looks good to me
no issues as far as i can see
[https://valkyriecrusade.fandom.com/wiki/The_Glaive_of_Valor](https://valkyriecrusade.fandom.com/wiki/The_Glaive_of_Valor)

**Comment by kushieda-minori** [comment]
Great! I did make the "Memory Core" links to the Items page, `[[Items#Memory Core|<memory core name>]]` so you may need to add a new `Memory Core` section to the items page. Or if you want to make a generic `Weapons` page and link there instead I can update it.

**Comment by Adriaantje** [comment]
Alright, thanks a lot!
I'll see what to do about the core item

**Comment by kushieda-minori** [comment]
actually... linking to here may be better: `[[Soul_Weapon#Upgrading_Soul_Weapon]]`... let me know

**Comment by Adriaantje** [comment]
huh, look at that. 
thats actually perfect :)

**Comment by kushieda-minori** [comment]
ok, I'll update the link then close out this ticket and the release.
