### ISSUE TITLE
runtime error when using latest game data (2020-01-22)

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#31]
When I try to load the game data of a few hours ago, I get an error stack when starting the grouper (and it doesnt start)
Using the same executable with data from a few days ago still works

```
$ Downloads/vc_file_grouper_OSX 2020-01-22_08-41-41/com.nubee.valkyriecrusade/files/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x12c6876]

goroutine 1 [running]:
zetsuboushita.net/vc_file_grouper/vc.renameSpecialAmalCardsWithDupNames()
	/home/john/git/go/src/zetsuboushita.net/vc_file_grouper/vc/card.go:1234 +0x166
zetsuboushita.net/vc_file_grouper/vc.Read(0x7fff5fbffc2b, 0x34, 0xc000071790, 0x7fff5fbffc2b, 0x34, 0x0, 0x0)
	/home/john/git/go/src/zetsuboushita.net/vc_file_grouper/vc/vcfile.go:327 +0x320
zetsuboushita.net/vc_file_grouper/vc.ReadMasterData(0x7fff5fbffc2b, 0x34, 0x1480120, 0xc0000640e0)
	/home/john/git/go/src/zetsuboushita.net/vc_file_grouper/vc/vcfile.go:50 +0x5b
main.main()
	src/zetsuboushita.net/vc_file_grouper/main.go:49 +0x1350

$ Downloads/vc_file_grouper_OSX 2020-01-16_09-31-52/com.nubee.valkyriecrusade/files/
Listening on port 8585. Connect to http://localhost:8585/
Press <CTRL>+C to stop or close the terminal.
```
Looks like a null reference in vc.renameSpecialAmalCardsWithDupNames()

I got the same error on Windows, but I didnt try to load old data yet.

**Comment by kushieda-minori** [comment]
ok, I'll try to take a look today

**Comment by kushieda-minori** [comment]
The root of the issue was misaligned indexes in the card data for `Angelic Oracle`. She has a card ID of `8452` or `8453`, but the list only has `8433` elements in it. Not only that, but the amalgamation data is incorrect for the cards in the system. It is referencing cards with IDs that don't exist, so I had to work around that. I'll bundle up a new release now that has this fix in it.
