### ISSUE TITLE
Demon Realm event Demon Core Exchange table empty

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#33]
I noticed the Demon Core exchange table is empty.
Not sure if this is because its not present in the game data, I couldn't find where to look.
Can you maybe look into it?

```
==Demon Core Exchange==
{| class="article-table mw-collapsible mw-collapsed" border="1" cellpadding="1" cellspacing="1"
|-
! scope="col" |Prize
! scope="col" |Cost
! scope="col" |Limit

|-
| prize || [[File:Demon Core.png|30px|link=]] xCost || limit
|}
```
[master_all.json.txt](https://github.com/kushieda-minori/vc_file_grouper/files/4147045/master_all.json.txt)

**Comment by kushieda-minori** [comment]
I looked at this previously in #23 . I'll see if they added it in, but I doubt they did.

**Comment by Adriaantje** [comment]
Hey kush,
I finally made this into a wiki template. Can you add it in the tool?
You can see it in action here:
https://valkyriecrusade.fandom.com/wiki/Chaotic_Catastrophe
Or, it looks like this:
```
==Demon Core Exchange==
{{DemonCoreExchange
|ur 1 = Siegfried
|ur 2 = Orvis
|ur amal = Gilles De Rais’s Memory
|old rr = Zelzal
|old rebirth = Secret Elixir (Jade)
|element = Dark
}}
```
Most of those can't be prefilled I think, but at least element should be possible right? it's also found at the top of the page.

**Comment by kushieda-minori** [comment]
I'll take a look, it shouldn't be too hard to swap out the sections. I'm not sure how much I could prefill though. Does the element in the template match the event element?

**Comment by Adriaantje** [comment]
Yes, it should match the current event shield element
