### ISSUE TITLE
New/unreleased cards mixed up

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#34]
The card list shows the unreleased card Super Angel, as well as Shmuel, but the skills and icons on their pages dont seem to match.
36310 shows some other icon, and doesnt seem to be linked to the others,
while 36877 shows Shmuel on the list, but Super Angel on the detail page.

Any idea whats going wrong here?
<img width="1442" alt="Screenshot 2020-02-03 at 10 21 25" src="https://user-images.githubusercontent.com/3531714/73640940-77983780-466f-11ea-8ca7-c18f01e52fed.png">
[master_all.json.txt](https://github.com/kushieda-minori/vc_file_grouper/files/4147045/master_all.json.txt)

**Comment by kushieda-minori** [comment]
It is probably just bad data from MyNet. I'll take a look though.

**Comment by kushieda-minori** [comment]
@Adriaantje, I never got a chance to confirm. was this just bad data?

**Comment by Adriaantje** [comment]
Oh right, I forgot.
That indeed looks to be the case, everything is normal again with the current data
