### ISSUE TITLE
wrong card & icon file names

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#35]
Before, the file names of the card images would be:
card name_icon.png
card name_H_icon.png
card name_G_icon.png
card name_X_icon.png
card name.png
card name_H.png
card name_X.png

just now, i got these files (while expecting the above, bottom to top):
![image](https://user-images.githubusercontent.com/3531714/74650116-46e0f380-5181-11ea-97cf-9d3faef00b04.png)

did you change something, or is the data fucked up again?
[master_all.json.txt](https://github.com/kushieda-minori/vc_file_grouper/files/4213452/master_all.json.txt)

**Comment by Adriaantje** [comment]
I should probably add that I did get the image I actually clicked on, it's just the name that was different

**Comment by kushieda-minori** [comment]
No. Probably something I missed with the path fixes I made a few weeks ago.
I'll try to get it fixed soon.

**Comment by kushieda-minori** [comment]
@Adriaantje , try this release and let me know if it worked: https://github.com/kushieda-minori/vc_file_grouper/releases/tag/v20200217-a

**Comment by Adriaantje** [comment]
Yep, fixed.
Thanks!
