### ISSUE TITLE
Add new Symbol property

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#39]
Cards can now have a Symbol, identified by a new property, e.g.
` "card_symbol_id": 1`
This corresponds to an image found in `files\battle\card_symbol`
(1.png, 2.png, 3.png)
Currently goes up to 3 in the data, with 1 being Sun, 2 being Sea and 3 being Earth.
0 means it doesnt have a symbol (yet).
the folder has images for up to 16 symbols though...

Can you look into providing this info via the tool?

I think a decent place on the wiki would be above or below the Availability. I looked at the Card template, but its pretty daunting, so if you could take a look at that too... much obliged.

[master_all.json.txt](https://github.com/kushieda-minori/vc_file_grouper/files/4622210/master_all.json.txt)

**Comment by kushieda-minori** [comment]
Have the symbol images been uploaded to the Wiki yet?

**Comment by Adriaantje** [comment]
> 
> 
> Have the symbol images been uploaded to the Wiki yet?

Yes, they are:
Symbol_Sun.png
Symbol_Sea.png
Symbol_Earth.png

**Comment by kushieda-minori** [comment]
bummer... I was hoping to just use the numbers Symbol_01.png ... Symbol_16.png

would it be OK if I just upload them as such?

**Comment by Adriaantje** [comment]
Yea that seems fine, i didnt really give much thought to the names anyway

**Comment by kushieda-minori** [comment]
Should there be an info page for the symbols?

**Comment by Adriaantje** [comment]
I've been thinking about it. for now i added some stuff to the tower page about it:
https://valkyriecrusade.fandom.com/wiki/Tower-Type_Event#Elite_difficulty_and_Symbols

not sure if it needs its own page

**Comment by kushieda-minori** [comment]
Should probably be it's own page. I'll make a symbol template to map the numbers to these name/images: (see my comment)
https://valkyriecrusade.fandom.com/wiki/User_blog:Adriaantje1/Cards_that_have_the_new_SYMBOL_feature

**Comment by kushieda-minori** [comment]
ok @Adriaantje, For now you can backfill the cards using the number like I did for https://valkyriecrusade.fandom.com/wiki/Celestial_Angel
```
|symbol = 3
```
which will add in the symbol and also add a new category:
https://valkyriecrusade.fandom.com/wiki/Category:Card_Symbol/Earth

1. Sun
2. Sea
3. Earth

If you want to have the symbol also link to a new info page, then you can update the template here:
https://valkyriecrusade.fandom.com/wiki/Template:Card/Symbol

You can also call the template without it triggering a category on the page
No Category call:
```
{{Card/Symbol|5}}
```
Trigger the category:
```
{{Card/Symbol|5|useCategory=any value here}}
```

**Comment by kushieda-minori** [comment]
also, for the template, if you don't like any of the names I picked for the symbols, now would be a good time to change them.

I'll try to get the code changes done shortly so the symbol can be populated from the program

**Comment by Adriaantje** [comment]
> 
> 
> also, for the template, if you don't like any of the names I picked for the symbols, now would be a good time to change them.
> 

I was wondering where you got the names for symbol 4+, did you make them up? 
Couldn't find the names in the data at least, maybe wait for official names on them

**Comment by kushieda-minori** [comment]
I made them up. I was really stumped for names on 12, 15, and 16...
