### ISSUE TITLE
Symbol bonus for tower and DRV events

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#40]
Tower and DRV events now have a property stating which symbol is advantageous.
Can you add this to the wiki text generation, so it can be added to the event template?
The property is called `symbol_bonus_group_id` :

```
  "mst_tower": [
<------>
    {
      "_id": 35,
      "element_id": 4,
      "enemy_symbol_id": 2,
      "ranking_reward_group_id": 35,
      "arrival_point_reward_group_id": 35,
      "level_skill_group_id": 1,
      "url_scheme_id": 224,
      "public_start_datetime": 1592535600,
      "public_end_datetime": 1593572399,
      "ranking_start_datetime": 1592535600,
      "ranking_end_datetime": 1594177199,
      "eventgacha_id": 14,
      "scenario_id": -1,
      "elemental_alignment_bonus_group_id": 1,
      "symbol_bonus_group_id": 1
    }
```

```
  "mst_dungeon": [
<------>
    {
      "_id": 17,
      "element_id": 2,
      "enemy_symbol_id": 3,
      "ranking_reward_group_id": 17,
      "arrival_point_reward_group_id": 17,
      "scenario_id": -1,
      "url_scheme_id": 221,
      "exchange_item_id": 812,
      "public_start_datetime": 1590980400,
      "public_end_datetime": 1591757999,
      "ranking_start_datetime": 1590980400,
      "ranking_end_datetime": 1592362799,
      "eventgacha_id": -1,
      "elemental_alignment_bonus_group_id": 1,
      "symbol_bonus_group_id": 1,
      "bg_top_image_id": 66,
      "bg_area_image_id": 2
    }
```

[master_all.json.txt](https://github.com/kushieda-minori/vc_file_grouper/files/4803783/master_all.json.txt)

**Comment by kushieda-minori** [comment]
I believe the one we want is `enemy_symbol_id`. It looks like `symbol_bonus_group_id` is used for something else

**Comment by kushieda-minori** [comment]
cleaned up some other small items on the event templates too, like detecting is there is a scenario/story.

**Comment by Adriaantje** [comment]
> I believe the one we want is `enemy_symbol_id`. It looks like `symbol_bonus_group_id` is used for something else

I thought enemy ID was the symbol the enemy uses, and bonus ID the symbol that is advantageous for that event.
The events currently show the shield element, not the element of the enemy. It seemed to me it should show either both the advantageous properties, or the enemy ones.
e.g. for the current event (https://valkyriecrusade.fandom.com/wiki/The_Tower_of_Planet_Life) show either dark + earth, or light + sea

**Comment by kushieda-minori** [comment]
The bonus ID is definitely not the advantage element. It's set to 1 for all the events that have symbols so far, I think it's more for some internal damage modifies that the code uses.

I updated the templates on the Wiki. How does that look now?

**Comment by Adriaantje** [comment]
Looking good. Thanks!
