### ISSUE TITLE
fix log location and folder name

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#54]
the debug log folder is placed in the path of the shell where the tool is run from, instead of the folder of the exe.
e.g. running it like
`PS D:\> .\Users\Adriaantje\Downloads\vc_file_grouper_Win64.exe `
creates the folder: 
`D:\changelog`

also, having "VC" in the folder name might be more sensible.

**Comment by kushieda-minori** [comment]
game is over. won't fix
