### ISSUE TITLE
Licorice and Guardian Licorice have empty skill

### ISSUE THREAD

**Issue by Adriaantje** [kushieda-minori/vc_file_grouper#56]
The cards Licorice and Guardian Licorice do not have skill effects in the tool.
The game data seems to have skill entries for them, so i assume some parsing is going wrong.

http://localhost:8585/cards/detail/5761
https://valkyriecrusade.fandom.com/wiki/Licorice

**Comment by Adriaantje** [comment]
![image](https://user-images.githubusercontent.com/3531714/106371675-5e4fc700-6367-11eb-95d8-cc30942af1f4.png)

okay... looks like the card itself is empty too...

i assume its a mynet fuckup then

**Comment by kushieda-minori** [comment]
closing since this is a data issue.
